### ISSUE TITLE
Set up Python linting

### ISSUE THREAD

**Issue by qwofford** [lanl/dsi#19]
pylama or similar on a pre-commit git hook should work

**Comment by DanielRJohnson** [comment]
Like Quincy said, pylama could be used if we wanted to go down this path. Having your commit fail due to small formatting errors can be frustrating, so an autoformatter like autopep8 `https://pypi.org/project/autopep8/` could be used. Whether the autoformatter is called automatically or manually is another question open for discussion, manually may get tedious but automatically leads to your code (kind of) changing without you knowing. Conforming to a standard is  valuable (currrently, pylama gives 303 warnings on qwofford/issue14), and I think this should be looked in to.

**Comment by qwofford** [comment]
Resolves with #18
